### ISSUE TITLE
single color variation of logo

### ISSUE THREAD

**Issue by yomed** [marko-js/branding#1]
Hi, do you have the single color versions of the logo available? Those variations would be useful for things like file icons. I noticed that the `.ai` file has black and white versions, but I had thought there was a colored one as well.

Or if you just have specific color desired, that would be fine too.

**Comment by patrick-steele-idem** [comment]
We only include the single color b/w variants, but for the logo on a dark background I would choose the blue (#43C0F0) as the primary color since it appears first in the logo:

![marko-logo](https://cloud.githubusercontent.com/assets/978214/14096836/ea9ade8c-f528-11e5-8127-f8eebb67d9c9.png)

The orangish yellow is not a bad option either (#FABD00):

![marko-logo-yellow](https://cloud.githubusercontent.com/assets/978214/14096854/08b41e56-f529-11e5-97d4-3bafdc1f04d5.png)

Which do you prefer?

**Comment by yomed** [comment]
I think it would be convenient to have the same color for both light and dark background, so I'd prefer a blue for that. Maybe slightly darker to work against white? The original logo has a lot of gradients, so you have some flexibility relative to that.

For example, slightly darker #3caee4 shown below:

<img width="278" alt="screen shot 2016-03-28 at 8 57 29 pm" src="https://cloud.githubusercontent.com/assets/3595986/14097606/b8b8cb50-f527-11e5-991e-ca960ae5711c.png">
<img width="303" alt="screen shot 2016-03-28 at 8 57 32 pm" src="https://cloud.githubusercontent.com/assets/3595986/14097607/b8b913da-f527-11e5-89e2-828d39b231e8.png">

**Comment by patrick-steele-idem** [comment]
@yomed Looks good to me. If you want to want to start using that as the single color variant I have no objections. Do you mind sending a PR to add those images to this repo?

**Comment by philidem** [comment]
I like the blue (#3caee4) options that @yomed provided. Definitely nice to have those!
